FROM pangeo/pangeo-notebook:2020.09.09
RUN /srv/conda/envs/notebook/bin/python -m pip install -U --no-deps git+https://github.com/TomAugspurger/distributed.git@2c8fefe2babcfc54baf87655d9f06823be9d303f
