FROM pangeo/pangeo-notebook:2021.06.05
RUN /srv/conda/envs/notebook/bin/python -m pip install -U --no-deps git+https://github.com/gjoseph92/distributed/@decide_worker/co-assign-relatives-2 git+https://github.com/dask/dask
