name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pangeo-dask=2021.01.16
  - pip=20
  - ipywidgets =7
  - jupyter-server-proxy =1.5.3
  - jupyterhub-singleuser =1.3.0
  - jupyterlab =2
  - nbgitpuller =0.9.0
  - nodejs >=12
  - pip:
    - git+https://github.com/TomAugspurger/dask-labextension.git@pangeo-fixup-test
