channels:
  - conda-forge
dependencies:
    - dask =2.14.0
    - distributed =2.14.0
    - dask-kubernetes =0.10.1
    - dask-gateway =0.7.1
    - dask-labextension =1.1*
    - jupyter-server-proxy =1.3*
    - jupyterhub =1.1*
    - jupyterlab =1.2*
    - nbgitpuller =0.8*
